repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        language_version: python3
        additional_dependencies:
          - flake8-bugbear==23.12.2
          - flake8-builtins==2.2.0
          - flake8-mutable==1.2.0
          - flake8-rst-docstrings==0.3.0
          - flake8-docstrings==1.7.0
  - repo: https://github.com/MiraGeoscience/pre-commit-hooks
    rev: v1.0.1
    hooks:
      - id: prepare-commit-msg
      - id: check-commit-msg
